"""Fast Analysis — artifact persistence (save/load workspace) + decoupled render.

This module is the **Capa B/C** persistence layer for the experimental
*Fast Analysis* workflow mode. It is intentionally self-contained:

* No Tkinter, no py4DSTEM imports — only ``numpy`` + ``matplotlib`` (Agg ``Figure``).
* It never touches ``single`` / ``batch`` code paths. ``pipeline.py`` is untouched.

Source of truth = numeric arrays (``strain_raw``) + ``strain_manifest.json`` +
``analysis_session.json``. PNGs are *export*, never the source of truth.

Layout written per scan (xarray/napari-ready for Phase 2)::

    gui_results_fast/<scan_stem>/
        data/
            strain_raw_without_roi.npz     # (H,W,3) fraction, channels [eyy,exx,exy]
            strain_raw_with_roi.npz        # same format (only if a W/ ROI pass exists)
            adf_realspace.npz              # (H,W) ADF for overlay / post-analysis
            strain_manifest.json           # calibration + provenance (Capa A snapshot)
            analysis_session.json          # view/analysis state (Capa C)
            INVALIDATION.md                # human + AI readable invalidation map
            stress_tensors_without_roi_Pa.npz   # compat with current export
            stress_tensors_with_roi_Pa.npz      # compat
            stress_meta_*.json                  # compat
            params.json                         # compat marker
        figures/                            # regenerable PNGs

The reload path restores ``state.strain_raw[label]`` verbatim, so
``pipeline.strain_tensor_components_from_state`` (and therefore stress, line
profiles and rendering) works again **without ever calling get_strain**.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

import numpy as np

# --------------------------------------------------------------------------- #
# Constants
# --------------------------------------------------------------------------- #

FAST_GUI_RESULTS_DIR = "gui_results_fast"

#: Channel order of the persisted ``(H,W,3)`` strain stack (py4DSTEM / notebook).
CHANNEL_ORDER = ("eyy", "exx", "exy")

#: Map-array labels we persist as full ``(H,W,3)`` tensors.
STRAIN_MAP_LABELS = ("without_roi", "with_roi")

_MANIFEST_NAME = "strain_manifest.json"
_SESSION_NAME = "analysis_session.json"
_INVALIDATION_NAME = "INVALIDATION.md"
_ADF_NAME = "adf_realspace.npz"
_ARTIFACT_VERSION = 1


INVALIDATION_MD = """\
# INVALIDATION MAP — Fast Analysis artifacts

Generated by `fast_artifacts.py`. Tells a human (and a future AI session) which
change invalidates which layer, so we only recompute what is genuinely stale.

| Change | Layer | Recompute? |
|---|---|---|
| Re-detect braggpeaks / detect params | A (pipeline) | **YES — heavy** (`find_Bragg_disks`) |
| Origin / Q pixel / basis | A | **YES — heavy** |
| `get_strain` parameters | A | **YES — heavy** |
| ROI Selector (unified) changed | A | **YES — heavy** (W/ ROI is a separate pass) |
| Strain W/O ROI vs W/ ROI | A | **YES — two distinct passes**, not a mask |
| Stress C11/C12/C44, plane stress/strain | B→C | Cheap — Hooke over saved ε |
| New / moved line, profile width | C | **NO** — resample saved array |
| vrange / vrange_theta / colormap / titles | C | **NO** — re-render |
| Refresh figures / export PNG/CSV/Summary | C | **NO** — re-export |
| Drift in line coordinates only | C | **NO** — shift endpoints + resample |
| Stats on a sub-region of an existing map | C | **NO** |

**Golden rule:** the `.npz` arrays + manifest are the source of truth. PNGs are export.

Reload is safe (no `get_strain`) when `strain_manifest.json.braggpeaks_mtime`
still matches the on-disk `braggpeaks.h5` mtime.
"""


# --------------------------------------------------------------------------- #
# Small helpers
# --------------------------------------------------------------------------- #

def _log(log: Callable[[str], None] | None, msg: str) -> None:
    if log is not None:
        try:
            log(msg)
        except Exception:
            pass


def _jsonable(obj: Any) -> Any:
    """Best-effort conversion of numpy / Path / tuple structures to JSON types."""
    if obj is None or isinstance(obj, (bool, int, float, str)):
        return obj
    if isinstance(obj, Path):
        return str(obj)
    if isinstance(obj, dict):
        return {str(k): _jsonable(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [_jsonable(v) for v in obj]
    if isinstance(obj, (np.integer,)):
        return int(obj)
    if isinstance(obj, (np.floating,)):
        return float(obj)
    if isinstance(obj, (np.bool_,)):
        return bool(obj)
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    # Fall back to string so json.dump never crashes the save.
    try:
        return str(obj)
    except Exception:
        return None


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def scan_stem(state: Any) -> str:
    raw = getattr(state, "raw_mib_path", None)
    if raw is not None:
        try:
            return Path(raw).stem
        except Exception:
            pass
    return "results"


def fast_results_root(state: Any, output_root: str | Path | None = None) -> Path:
    """``<raw parent>/gui_results_fast`` by default; never ``gui_results/`` (single)."""
    if output_root is not None:
        return Path(output_root).expanduser()
    raw = getattr(state, "raw_mib_path", None)
    base = Path(raw).parent if raw is not None else Path.cwd()
    return base / FAST_GUI_RESULTS_DIR


def fast_scan_dir(state: Any, output_root: str | Path | None = None) -> Path:
    return fast_results_root(state, output_root) / scan_stem(state)


def _structured_to_hw3(S: np.ndarray) -> np.ndarray | None:
    """Structured strain array (named fields) → ``(H,W,3)`` stack [eyy, exx, exy]."""
    names = {str(n).lower(): n for n in (S.dtype.names or ())}

    def pick(*cands: str) -> Any:
        for c in cands:
            if c in names:
                return names[c]
        return None

    n_eyy = pick("e_yy", "eyy", "eps_yy")
    n_exx = pick("e_xx", "exx", "eps_xx")
    n_exy = pick("e_xy", "exy", "eps_xy")
    if not (n_eyy and n_exx and n_exy):
        return None
    try:
        return np.stack(
            [
                np.asarray(S[n_eyy], dtype=float),
                np.asarray(S[n_exx], dtype=float),
                np.asarray(S[n_exy], dtype=float),
            ],
            axis=-1,
        )
    except Exception:
        return None


def _as_hw3(arr: Any) -> np.ndarray | None:
    """Coerce a raw strain entry to ``(H,W,3)`` float32 [eyy, exx, exy], or ``None``.

    py4DSTEM ``strainmap_g1g2.data`` often carries extra channels (theta, mask) and
    may put the channel axis first, e.g. ``(5,H,W)`` or ``(H,W,5)``. We mirror
    ``pipeline._strain_channel``: the channel axis is the last (or first) axis with
    size 3–8, and we keep the first three channels (eyy, exx, exy) by index.
    """
    if arr is None:
        return None
    try:
        S = np.asarray(arr)
    except Exception:
        return None
    if S.dtype.names:  # structured array → stack named fields
        st = _structured_to_hw3(S)
        if st is None:
            return None
        S = st
    S = np.squeeze(S)
    if S.ndim != 3:
        return None
    if 3 <= S.shape[-1] <= 8:
        chan_last = S
    elif 3 <= S.shape[0] <= 8:
        chan_last = np.moveaxis(S, 0, -1)
    else:
        return None
    # Keep eyy/exx/exy (channels 0,1,2); drop theta/mask if present.
    return np.ascontiguousarray(chan_last[..., :3], dtype=np.float32)


def _adf_from_state(state: Any) -> np.ndarray | None:
    vis = getattr(state, "virtual_images", None) or {}
    for key in ("annular_dark_field", "ADF", "adf"):
        obj = vis.get(key)
        if obj is None:
            continue
        try:
            arr = np.asarray(getattr(obj, "data", obj), dtype=np.float32)
        except Exception:
            continue
        if arr.ndim == 2:
            return np.ascontiguousarray(arr)
    return None


def _file_mtime(path: Any) -> float | None:
    try:
        p = Path(path)
        if p.is_file():
            return float(p.stat().st_mtime)
    except Exception:
        pass
    return None


# --------------------------------------------------------------------------- #
# Manifest (Capa A snapshot) — built from WorkflowState
# --------------------------------------------------------------------------- #

def build_manifest(state: Any) -> dict[str, Any]:
    """Provenance + calibration snapshot. Best-effort; missing fields → null."""
    raw = getattr(state, "raw_mib_path", None)
    bragg = getattr(state, "braggpeaks_path", None)

    without = _as_hw3(getattr(state, "strain_raw", {}).get("without_roi"))
    image_shape = list(without.shape[:2]) if without is not None else None

    origin_xy = None
    cg = getattr(state, "center_guess", None)
    if isinstance(cg, (list, tuple)) and len(cg) == 2:
        # center_guess is (y, x) in this codebase's convention.
        origin_xy = [int(cg[0]), int(cg[1])]

    calstate = {
        "origin_done": bool(getattr(state, "origin_fit", None) is not None
                            or getattr(state, "origin_measurement", None) is not None),
        "ellipse_done": bool(getattr(state, "p_ellipse", None) is not None),
        "q_pixel_done": getattr(state, "q_pixel_size", None) is not None,
        "basis_done": bool(getattr(state, "strainmap_full", None) is not None
                           or getattr(state, "strainmap_roi", None) is not None),
        "strain_without_roi": "without_roi" in (getattr(state, "strain_raw", {}) or {}),
        "strain_with_roi": "with_roi" in (getattr(state, "strain_raw", {}) or {}),
    }

    manifest: dict[str, Any] = {
        "artifact_version": _ARTIFACT_VERSION,
        "stem": scan_stem(state),
        "raw_path": str(raw) if raw is not None else None,
        "image_shape": image_shape,
        "r_pixel_nm": getattr(state, "image_pixel_size", None),
        "r_pixel_units": getattr(state, "image_pixel_units", "nm"),
        "q_pixel_size": getattr(state, "q_pixel_size", None),
        "q_pixel_units": getattr(state, "q_pixel_units", "A^-1"),
        "origin_xy": origin_xy,
        # g1/g2 fitted reciprocal vectors live inside the StrainMap object and are
        # not reliably recoverable post-hoc; recorded as null when unknown.
        "g1_qxy": None,
        "g2_qxy": None,
        "calstate": calstate,
        "strain_params": _jsonable(getattr(state, "strain_params", {})),
        "strain_basis_params": _jsonable(getattr(state, "strain_basis_params", {})),
        "roi_bounds": _jsonable(getattr(state, "roi_bounds", None)),
        "strain_scan_roi_bounds": _jsonable(getattr(state, "strain_scan_roi_bounds", None)),
        "braggpeaks_path": str(bragg) if bragg is not None else None,
        "braggpeaks_mtime": _file_mtime(bragg),
        "channel_order": list(CHANNEL_ORDER),
        "units": {"strain": "fraction", "stress": "Pa"},
        "timestamps": {"compute": _now_iso()},
        # xarray-ready schema hint for Phase 2 (napari / xarray.Dataset(dim=scan)).
        "layout": {
            "dims": ["y", "x"],
            "strain_vars": {"eyy": 0, "exx": 1, "exy": 2},
            "stress_vars": ["sigma_xx", "sigma_yy", "sigma_xy"],
            "extra_vars": ["adf"],
        },
    }
    return manifest


# --------------------------------------------------------------------------- #
# SAVE — workspace
# --------------------------------------------------------------------------- #

def save_fast_artifacts(
    state: Any,
    session: dict[str, Any] | None = None,
    *,
    output_root: str | Path | None = None,
    save_figures: bool = True,
    log: Callable[[str], None] | None = None,
) -> dict[str, Any]:
    """Persist the Fast Analysis workspace for the current scan.

    Returns a dict with ``scan_dir`` / ``data_dir`` / ``figures_dir`` and a
    ``written`` list of every file path created.
    """
    scan_dir = fast_scan_dir(state, output_root)
    data_dir = scan_dir / "data"
    fig_dir = scan_dir / "figures"
    data_dir.mkdir(parents=True, exist_ok=True)
    fig_dir.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []
    strain_raw = getattr(state, "strain_raw", {}) or {}

    # --- (H,W,3) strain tensors -------------------------------------------- #
    n_tensors = 0
    for label in STRAIN_MAP_LABELS:
        S = _as_hw3(strain_raw.get(label))
        if S is None:
            continue
        path = data_dir / f"strain_raw_{label}.npz"
        np.savez_compressed(path, strain=S, channel_order=np.asarray(CHANNEL_ORDER))
        written.append(path)
        n_tensors += 1
        _log(log, f"  saved {path.name}  shape={S.shape} (channels {CHANNEL_ORDER})")
    if n_tensors == 0:
        _log(log, "  WARNING: no strain_raw tensors to save — compute strain first.")

    # --- ADF real-space ---------------------------------------------------- #
    adf = _adf_from_state(state)
    if adf is not None:
        path = data_dir / _ADF_NAME
        np.savez_compressed(path, adf=adf)
        written.append(path)
        _log(log, f"  saved {path.name}  shape={adf.shape}")

    # --- stress tensors (compat with current export) ----------------------- #
    stress = getattr(state, "stress_tensors_pa", {}) or {}
    stress_meta = getattr(state, "stress_meta", {}) or {}
    for label, sd in stress.items():
        if not isinstance(sd, dict):
            continue
        try:
            path = data_dir / f"stress_tensors_{label}_Pa.npz"
            np.savez_compressed(
                path,
                sigma_xx=np.asarray(sd["sigma_xx"]),
                sigma_yy=np.asarray(sd["sigma_yy"]),
                sigma_xy=np.asarray(sd["sigma_xy"]),
            )
            written.append(path)
        except Exception as exc:
            _log(log, f"  note: could not save stress {label}: {exc}")
            continue
        meta = stress_meta.get(label)
        if meta:
            mpath = data_dir / f"stress_meta_{label}.json"
            mpath.write_text(json.dumps(_jsonable(meta), indent=2), encoding="utf-8")
            written.append(mpath)

    # --- manifest ---------------------------------------------------------- #
    manifest = build_manifest(state)
    manifest["timestamps"]["export"] = _now_iso()
    manifest["written_files"] = [p.name for p in written]
    mpath = data_dir / _MANIFEST_NAME
    mpath.write_text(json.dumps(_jsonable(manifest), indent=2), encoding="utf-8")
    written.append(mpath)
    _log(log, f"  saved {mpath.name}")

    # --- analysis session (Capa C) ----------------------------------------- #
    session_out = _jsonable(session or {})
    if not isinstance(session_out, dict):
        session_out = {}
    session_out.setdefault("saved_at", _now_iso())
    spath = data_dir / _SESSION_NAME
    spath.write_text(json.dumps(session_out, indent=2), encoding="utf-8")
    written.append(spath)
    _log(log, f"  saved {spath.name}")

    # --- INVALIDATION.md --------------------------------------------------- #
    ipath = data_dir / _INVALIDATION_NAME
    ipath.write_text(INVALIDATION_MD, encoding="utf-8")
    written.append(ipath)

    # --- params.json marker (compat) --------------------------------------- #
    ppath = data_dir / "params.json"
    ppath.write_text(
        json.dumps(
            {
                "source": "fast_analysis",
                "stem": manifest["stem"],
                "strain_params": manifest["strain_params"],
                "roi_bounds": manifest["roi_bounds"],
                "q_pixel_size": manifest["q_pixel_size"],
                "r_pixel_nm": manifest["r_pixel_nm"],
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    written.append(ppath)

    # --- figures (regenerable PNGs) ---------------------------------------- #
    if save_figures:
        for attr, prefix in (
            ("calibration_figures", "calibration"),
            ("strain_figures",      "strain"),
            ("stress_figures",      "stress"),
        ):
            figs = getattr(state, attr, {}) or {}
            for key, fig in figs.items():
                if fig is None or not hasattr(fig, "savefig"):
                    continue
                safe = str(key).replace("/", "_").replace(" ", "_")
                path = fig_dir / f"{prefix}_{safe}.png"
                try:
                    fig.savefig(path, dpi=200, bbox_inches="tight")
                    written.append(path)
                except Exception as exc:
                    _log(log, f"  note: could not save figure {key}: {exc}")

    _log(log, f"Saved Fast Analysis workspace → {scan_dir}  ({len(written)} files)")
    return {
        "scan_dir": scan_dir,
        "data_dir": data_dir,
        "figures_dir": fig_dir,
        "manifest": manifest,
        "written": written,
    }


# --------------------------------------------------------------------------- #
# LOAD — workspace
# --------------------------------------------------------------------------- #

def _resolve_data_dir(path: str | Path) -> Path:
    """Accept a scan dir, its ``data`` subdir, or the manifest file itself."""
    p = Path(path).expanduser()
    if p.is_file() and p.name == _MANIFEST_NAME:
        return p.parent
    if (p / "data" / _MANIFEST_NAME).is_file():
        return p / "data"
    if (p / _MANIFEST_NAME).is_file():
        return p
    # Default: treat as data dir.
    return p


def manifest_is_fresh(manifest: dict[str, Any]) -> tuple[bool, str]:
    """True when braggpeaks.h5 on disk still matches the recorded mtime."""
    bp = manifest.get("braggpeaks_path")
    rec = manifest.get("braggpeaks_mtime")
    if not bp:
        return True, "no braggpeaks recorded — reload arrays as-is"
    cur = _file_mtime(bp)
    if cur is None:
        return True, f"braggpeaks file not found ({bp}) — reload arrays as-is"
    if rec is None:
        return True, "no recorded mtime — reload arrays as-is"
    if abs(float(cur) - float(rec)) < 1e-6:
        return True, "braggpeaks mtime matches — reload is safe (no get_strain)"
    return False, "braggpeaks.h5 changed since save — Capa A may be stale; recompute recommended"


def load_fast_artifacts(
    state: Any,
    path: str | Path,
    *,
    log: Callable[[str], None] | None = None,
) -> dict[str, Any]:
    """Hydrate ``state`` from a saved Fast Analysis workspace — **no get_strain**.

    Restores ``strain_raw`` tensors, ADF, calibration scalars, strain params,
    ROI bounds and braggpeaks path. Returns the manifest plus a freshness flag
    and the parsed session under keys ``manifest`` / ``session`` / ``fresh`` /
    ``freshness_reason`` / ``data_dir``.
    """
    data_dir = _resolve_data_dir(path)
    mpath = data_dir / _MANIFEST_NAME
    if not mpath.is_file():
        raise FileNotFoundError(f"No {_MANIFEST_NAME} in {data_dir}")

    manifest = json.loads(mpath.read_text(encoding="utf-8"))
    _log(log, f"Loading Fast Analysis workspace from {data_dir}")

    # --- strain tensors ---------------------------------------------------- #
    if not hasattr(state, "strain_raw") or state.strain_raw is None:
        state.strain_raw = {}
    n = 0
    for label in STRAIN_MAP_LABELS:
        npz = data_dir / f"strain_raw_{label}.npz"
        if not npz.is_file():
            continue
        with np.load(npz, allow_pickle=False) as d:
            arr = np.asarray(d["strain"], dtype=np.float32)
        state.strain_raw[label] = arr
        n += 1
        _log(log, f"  loaded strain_raw[{label!r}] shape={arr.shape}")
    if n == 0:
        _log(log, "  WARNING: no strain_raw_*.npz found in workspace.")

    # --- ADF --------------------------------------------------------------- #
    adf_path = data_dir / _ADF_NAME
    if adf_path.is_file():
        try:
            with np.load(adf_path, allow_pickle=False) as d:
                adf = np.asarray(d["adf"], dtype=np.float32)
            if not hasattr(state, "virtual_images") or state.virtual_images is None:
                state.virtual_images = {}
            # Stored as a bare ndarray; downstream uses getattr(obj,"data",obj).
            state.virtual_images["annular_dark_field"] = adf
            _log(log, f"  loaded adf_realspace shape={adf.shape}")
        except Exception as exc:
            _log(log, f"  note: could not load ADF: {exc}")

    # --- stress tensors (optional) ----------------------------------------- #
    if not hasattr(state, "stress_tensors_pa") or state.stress_tensors_pa is None:
        state.stress_tensors_pa = {}
    for label in STRAIN_MAP_LABELS:
        sp = data_dir / f"stress_tensors_{label}_Pa.npz"
        if not sp.is_file():
            continue
        try:
            with np.load(sp, allow_pickle=False) as d:
                state.stress_tensors_pa[label] = {
                    "sigma_xx": np.asarray(d["sigma_xx"]),
                    "sigma_yy": np.asarray(d["sigma_yy"]),
                    "sigma_xy": np.asarray(d["sigma_xy"]),
                }
        except Exception:
            continue

    # --- calibration scalars + params -------------------------------------- #
    def _set(attr: str, value: Any) -> None:
        if value is not None and hasattr(state, attr):
            try:
                setattr(state, attr, value)
            except Exception:
                pass

    raw_path = manifest.get("raw_path")
    if raw_path:
        try:
            state.raw_mib_path = Path(raw_path)
        except Exception:
            pass
    _set("image_pixel_size", manifest.get("r_pixel_nm"))
    _set("q_pixel_size", manifest.get("q_pixel_size"))
    if manifest.get("strain_params"):
        _set("strain_params", manifest["strain_params"])
    if manifest.get("strain_basis_params"):
        _set("strain_basis_params", manifest["strain_basis_params"])
    rb = manifest.get("roi_bounds")
    if isinstance(rb, (list, tuple)) and len(rb) == 4:
        _set("roi_bounds", tuple(int(v) for v in rb))
    srb = manifest.get("strain_scan_roi_bounds")
    if isinstance(srb, (list, tuple)) and len(srb) == 4:
        _set("strain_scan_roi_bounds", tuple(int(v) for v in srb))
    bp = manifest.get("braggpeaks_path")
    if bp:
        try:
            state.braggpeaks_path = Path(bp)
        except Exception:
            pass

    # --- analysis session -------------------------------------------------- #
    session: dict[str, Any] = {}
    spath = data_dir / _SESSION_NAME
    if spath.is_file():
        try:
            session = json.loads(spath.read_text(encoding="utf-8"))
        except Exception as exc:
            _log(log, f"  note: could not parse session: {exc}")

    fresh, reason = manifest_is_fresh(manifest)
    _log(log, f"  freshness: {'FRESH' if fresh else 'STALE'} — {reason}")

    return {
        "manifest": manifest,
        "session": session,
        "fresh": fresh,
        "freshness_reason": reason,
        "data_dir": data_dir,
    }


# --------------------------------------------------------------------------- #
# Decoupled render (Capa C) — matplotlib only, embeddable in Tk
# --------------------------------------------------------------------------- #

def _channel(raw_hw3: np.ndarray, name: str) -> np.ndarray:
    idx = {"eyy": 0, "exx": 1, "exy": 2}[name]
    return np.asarray(raw_hw3[..., idx], dtype=float)


def render_strain_figure(
    raw: Any,
    *,
    vrange: tuple[float, float] = (-2.0, 2.0),
    cmap: str | dict[str, str] = "RdBu_r",
    adf_overlay: Any = None,
    roi_bounds: Any = None,
    as_percent: bool = True,
    title: str | None = None,
):
    """Render εxx / εyy / εxy (+ optional ADF) from a ``(H,W,3)`` raw tensor.

    Pure render — no recompute. ``vrange`` is in percent when ``as_percent`` is
    True (matches the GUI's ``get_strain.vrange`` convention). ``cmap`` may be a
    single name or a ``{"exx":..,"eyy":..,"exy":..}`` dict. Returns a
    ``matplotlib.figure.Figure`` (Agg) ready for ``FigureCanvasTkAgg``.
    """
    from matplotlib.figure import Figure

    S = _as_hw3(raw)
    if S is None:
        raise ValueError("render_strain_figure needs a (H,W,3) strain tensor.")

    scale = 100.0 if as_percent else 1.0
    unit = "%" if as_percent else "frac"
    vmin, vmax = float(vrange[0]), float(vrange[1])

    panels = [("exx", "ε_xx"), ("eyy", "ε_yy"), ("exy", "ε_xy")]
    has_adf = False
    adf = None
    if adf_overlay is not None:
        try:
            adf = np.asarray(getattr(adf_overlay, "data", adf_overlay), dtype=float)
            has_adf = adf.ndim == 2
        except Exception:
            has_adf = False
    ncols = len(panels) + (1 if has_adf else 0)

    fig = Figure(figsize=(4.2 * ncols, 4.0), constrained_layout=True)

    def _cmap_for(ch: str) -> str:
        if isinstance(cmap, dict):
            return cmap.get(ch, "RdBu_r")
        return cmap

    for i, (ch, label) in enumerate(panels):
        ax = fig.add_subplot(1, ncols, i + 1)
        data = _channel(S, ch) * scale
        im = ax.imshow(data, cmap=_cmap_for(ch), vmin=vmin, vmax=vmax, aspect="equal")
        ax.set_title(f"{label} ({unit})")
        ax.set_xticks([])
        ax.set_yticks([])
        fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
        _draw_roi(ax, roi_bounds)

    if has_adf:
        ax = fig.add_subplot(1, ncols, ncols)
        ax.imshow(adf, cmap="gray", aspect="equal")
        ax.set_title("ADF")
        ax.set_xticks([])
        ax.set_yticks([])
        _draw_roi(ax, roi_bounds)

    if title:
        fig.suptitle(title, fontsize=11)
    return fig


def _draw_roi(ax, roi_bounds: Any) -> None:
    if not (isinstance(roi_bounds, (list, tuple)) and len(roi_bounds) == 4):
        return
    try:
        from matplotlib.patches import Rectangle

        x0, x1, y0, y1 = (float(v) for v in roi_bounds)
        ax.add_patch(
            Rectangle(
                (x0, y0), x1 - x0, y1 - y0,
                fill=False, edgecolor="lime", linewidth=1.4,
            )
        )
    except Exception:
        pass
